// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"backendTemp/internal/controller"
	"backendTemp/internal/repository"
	"backendTemp/internal/router"
	"backendTemp/internal/service"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func InitializeApp(db *mongo.Database) (*gin.Engine, error) {
	userRepository := repository.NewUserRepository(db)
	authService := service.NewAuthService(userRepository)
	authController := controller.NewAuthController(authService)
	controllers := &router.Controllers{
		AuthController: authController,
	}
	engine := router.SetupRouter(controllers)
	return engine, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewUserRepository)

var ServiceSet = wire.NewSet(service.NewAuthService)

var ControllerSet = wire.NewSet(controller.NewAuthController, wire.Struct(new(router.Controllers), "*"))
